external-api:
  url: http://bmw.external.com

quarkus:
  http:
    cors:
      ~: true
      origins: "http://localhost:4200"
      methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      headers: "accept, authorization, content-type"
      exposed-headers: "location"
      access-control-allow-credentials: true
  rest-client:
    external-api:
      url: ${external-api.url}
  log:
    level: INFO
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
  index-dependency:
    workstation-rack-module:
      group-id: com.ctw.workstation
      artifact-id: workstation-rack-module
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
      reuse: false
      image-name: "postgres:14.10-alpine"
      container-env:
        "POSTGRES_DB": "workstation-rack"
        "POSTGRES_USER": "postgres"
        "PASSWORD": "postgres"
      port: 5433
      volumes:
        "db/init-db": "/docker-entrypoint-initdb.d"
      db-name: "workstation-rack"
      username: "postgres"
      password: "postgres"
    jdbc:
      url: jdbc:postgresql://localhost:5433/workstation-rack
      initial-size: 2
      min-size: 2
      max-size: 5

  liquibase:
    migrate-at-start: true
    search-path:
      - "src/main/resources/db"
    change-log: "changelog.xml"

  hibernate-orm:
    packages: com.ctw.workstation
    validate-in-dev-mode: false
    database:
      generation: none
    log:
      sql: ${hibernate_orm_log_sql:false}

